### ISSUE TITLE
Error running example

### ISSUE THREAD

**Issue by seanpackham** [a13X-B/bitumbra#1]
Hi, the library looks interesting. It is always great to have more [lighting/shadow options](https://github.com/love2d-community/awesome-love2d?tab=readme-ov-file#lighting). I like how minimal your solution is.

I tried running the example from the README.md and got the following error using LOVE 11.5:

```
Error

bitumbra.lua:209: Texture's type (array) must match the type of the shader's main texture type (2d).


Traceback

[love "callbacks.lua"]:228: in function 'handler'
[C]: in function 'drawLayer'
bitumbra.lua:209: in function 'draw'
main.lua:46: in function 'draw'
[love "callbacks.lua"]:168: in function <[love "callbacks.lua"]:144>
[C]: in function 'xpcall'
```

Thank you for sharing your work!

**Comment by a13X-B** [comment]
whoops, didn't mean to close yet.
it's a known bug and the fix is coming later today
